export const FOCUS_AREA_LABELS = [
  "AI",
  "Artists",
  "Blockchain",
  "Cultural Strategy",
  "Data",
  "Ecology",
  "Economy",
  "Gaming",
  "Governance",
  "Infrastructure",
  "Interoperability",
  "Legal",
  "Ownership",
  "Policy",
  "Public Value",
  "Robotics",
  "Simulation",
  "Stewardship",
  "Systems",
  "Virtual Environments",
  "Worldbuilding",
] as const;

export const ACTIVITY_TYPE_LABELS = [
  "Artist Talk",
  "Case Studies",
  "Commission",
  "Community Calls",
  "Editorial",
  "Events",
  "Exhibition",
  "Interview",
  "Lab",
  "Launch",
  "Measurements of Success",
  "Networks",
  "New Technologies",
  "Panel",
  "Partnerships",
  "Playthrough",
  "Proposals",
  "Prototyping",
  "Publication",
  "R&D",
  "Report",
  "Strategy",
] as const;

export const FORMAT_LABELS = [
  "Long-form",
  "Short-form",
  "Audio",
  "Video",
  "Interactive",
  "Dataset",
  "PDF",
] as const;

/** Partner / network names (Network row in the filter menu; also used on content rows). */
export const NETWORK_LABELS = [
  "RadicalxChange",
  "Aerocene Foundation",
  "Serpentine",
  "New Museum",
  "Tate",
  "e-flux",
  "DECAL",
  "FAE Core",
  "Ethereum Foundation",
  "Creative Europe",
  "Arts Council England",
  "Goethe-Institut",
  "Mozilla",
  "W3C",
  "IPFS",
  "Filecoin",
  "Zora",
  "Mirror",
  "Agnes",
  "Serpentine R&D",
] as const;
