export const FOCUS_AREA_LABELS = [
  "AI",
  "Artists",
  "Blockchain",
  "Cultural Strategy",
  "Data",
  "Ecology",
  "Economy",
  "Gaming",
  "Governance",
  "Infrastructure",
  "Interoperability",
  "Legal",
  "Ownership",
  "Policy",
  "Public Value",
  "Robotics",
  "Simulation",
  "Stewardship",
  "Systems",
  "Virtual Environments",
  "Worldbuilding",
] as const;

export const ACTIVITY_TYPE_LABELS = [
  "Artist Talk",
  "Case Studies",
  "Commission",
  "Community Calls",
  "Editorial",
  "Events",
  "Exhibition",
  "Interview",
  "Lab",
  "Launch",
  "Measurements of Success",
  "Networks",
  "New Technologies",
  "Panel",
  "Partnerships",
  "Playthrough",
  "Proposals",
  "Prototyping",
  "Publication",
  "R&D",
  "Report",
  "Strategy",
] as const;

/** Text labels for non-icon contexts; Format UI uses `format/formatItems.ts` (5 icon buttons). */
export const FORMAT_LABELS = [
  "Long-form",
  "Short-form",
  "Audio",
  "Video",
  "Interactive",
  "Dataset",
  "PDF",
] as const;
